def generate_book_author_data(author_data: dict, book_data: dict) -> dict:
  """
  Generates a dictionary representing a relationship between a book and an author.

  Args:
      author_data (dict): A dictionary containing author information generated by `generate_author_data`.
      book_data (dict): A dictionary containing book information generated by `generate_book_data`.

  Returns:
      (dict): A dictionary representing a book-author relationship with the following keys:
          - author_id (int): The unique identifier of the author.
          - book_id (int): The unique identifier of the book.
  """

  return {
      'author_id': author_data['author_id'],
      'book_id': book_data['book_id']
  }